@startuml COLORS

' BLACK COLOR
!define STYLE_COLOR_BLACK_DARK #000
!define STYLE_COLOR_BLACK #263238
!define STYLE_COLOR_BLACK_LIGHT #4f5b62

' GREY COLOR
!define STYLE_COLOR_BLACK_DARK #373737
!define STYLE_COLOR_BLACK #616161
!define STYLE_COLOR_BLACK_LIGHT #8e8e8e

' BROWN COLOR
!define STYLE_COLOR_BROWN_DARK #4b2c20
!define STYLE_COLOR_BROWN #795548
!define STYLE_COLOR_BROWN_LIGHT #a98274

' ORANGE COLOR
!define STYLE_COLOR_ORANGE_DARK #c66900
!define STYLE_COLOR_ORANGE #ff9800
!define STYLE_COLOR_ORANGE_LIGHT #ffc947

' YELLOW COLOR
!define STYLE_COLOR_YELLOW_DARK #c8b900
!define STYLE_COLOR_YELLOW #ffeb3b
!define STYLE_COLOR_YELLOW_LIGHT #ffff72

' GREEN COLOR
!define STYLE_COLOR_GREEN_DARK #087f23
!define STYLE_COLOR_GREEN #4caf50
!define STYLE_COLOR_GREEN_LIGHT #80e27e

' BLUE COLOR
!define STYLE_COLOR_BLUE_DARK #0069c0
!define STYLE_COLOR_BLUE #2196f3
!define STYLE_COLOR_BLUE_LIGHT #6ec6ff

' PURPLE COLOR
!define STYLE_COLOR_DEEP_ORANGE_DARK #6a0080
!define STYLE_COLOR_DEEP_ORANGE #9c27b0
!define STYLE_COLOR_DEEP_ORANGE_LIGHT #d05ce3

' PINK COLOR
!define STYLE_COLOR_PINK_DARK #c60055
!define STYLE_COLOR_PINK #ff4081
!define STYLE_COLOR_PINK_LIGHT #ff79b0

' RED COLOR
!define STYLE_COLOR_RED_DARK #c50e29
!define STYLE_COLOR_RED #ff5252
!define STYLE_COLOR_RED_LIGHT #ff867f

@enduml