@startuml "Action"

(*) --> "POST action"

--> "request new client token"
--> "request server token"
-> "connect to websocket server"
--> "send:\n - server token\n - client token\n - action with result"
--> "auth server token"
--> "send to everybody change"
-left-> action response
--> (*)
@enduml