@startuml "Websocket"
!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

actor Client as c
participant "HTTP server" as http
participant "Websocket server" as ws

c -> http : POST action
http <- http : - verify client\n- generate hmac with public key and secret key
http -> ws : - hash \n- action with result
ws -> ws : - verify hash
ws -> everyone : broadcast action with result
http -> c : - action status
@enduml